all:
	cc -Wall -Wextra -Werror *.c
1:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=1
42:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=42
100:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=100
1000:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=1000
10000:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=10000
minus:
	cc -Wall -Wextra -Werror *.c -D BUFFER_SIZE=-1